### ISSUE TITLE
Google SignIn Fails

### ISSUE THREAD

**Issue by bebaoboy** [maheshmnj/vocabhub#54] opened 2024-07-04 11:27 UTC
**Describe the bug**
I cannot sign in using my Google account.

**To Reproduce**
1. Open the app
2. Click on Sign In with Google

**Expected behavior**
Can sign up using Google Account.

**Screenshots**
![Screenshot_2024-07-04-18-24-45-829_com.vocabhub.app.jpg](https://github.com/maheshmnj/vocabhub/assets/74720131/a0ce481d-4b44-4510-9b48-79c1a6092036)

**Smartphone (please complete the following information):**
 - Device: Mi 11T
 - OS: Android 14, HyperOS
 

**Additional context**

**Comment by maheshmnj** [comment] 2024-07-04 23:43
Thanks for reporting, I have had similar reports before, But I am not able to reproduce that on my end. I will take a look at it soon. I believe this is an issue with SHA-1 key. If you have any insights feel free to share.

**Comment by maheshmnj** [comment] 2024-07-07 00:09
@bebaoboy  Can you try the Google SignIn now? I added the new keys to Firebase

**Comment by bebaoboy** [comment] 2024-07-07 01:27
Um still same error @maheshmnj

**Comment by maheshj01** [comment] 2024-07-08 05:22
Released a new version in store, updating the app should fix it.

**Comment by bebaoboy** [comment] 2024-07-08 05:25
Thank you, I signed in successfully. Will rate the app today 😍
![Screenshot_2024-07-08-12-24-49-407_com.vocabhub.app.jpg](https://github.com/maheshmnj/vocabhub/assets/74720131/a80dec58-11d3-4881-8aba-2a741bc72ba9)

**Comment by maheshj01** [comment] 2024-07-08 13:09
Thanks you so much for filing the issue or this would have gone unnoticed. Feel free to file issues you see in the app and I also added a [Contributing guideline](https://github.com/maheshmnj/vocabhub/blob/main/Contributing.md) if you are interested.

Closing as fixed!

**Closed by maheshj01** 2024-07-08 13:09 UTC
Labels: bug, waiting for author's response, P1
